# create Pandas Series

In [1]:
import pandas as pd

In [2]:
a = pd.Series([56,78,8,10,34])

In [3]:
a

0    56
1    78
2     8
3    10
4    34
dtype: int64

In [4]:
type(a)

pandas.core.series.Series

In [5]:
a

0    56
1    78
2     8
3    10
4    34
dtype: int64

In [6]:
a[3]

10

In [7]:
a[2:4]

2     8
3    10
dtype: int64

In [8]:
a = pd.Series(['soc','python','Java'])

In [9]:
a

0       soc
1    python
2      Java
dtype: object

In [4]:
a = pd.date_range(start = '01-7-2019', end = '30-8-2019')

In [5]:
a

DatetimeIndex(['2019-01-07', '2019-01-08', '2019-01-09', '2019-01-10',
               '2019-01-11', '2019-01-12', '2019-01-13', '2019-01-14',
               '2019-01-15', '2019-01-16',
               ...
               '2019-08-21', '2019-08-22', '2019-08-23', '2019-08-24',
               '2019-08-25', '2019-08-26', '2019-08-27', '2019-08-28',
               '2019-08-29', '2019-08-30'],
              dtype='datetime64[ns]', length=236, freq='D')

In [12]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# Pandas dataframe

In [6]:
import numpy as np

In [9]:
temp = np.random.randint(low = 20, high =100, size = [10,])
name = np.random.choice(['nabin','vamsi','parth','satish'],size=10)
random = np.random.choice([10,11,13,12,14],10)

In [10]:
random

array([12, 12, 13, 14, 10, 11, 13, 13, 14, 12])

In [11]:
name

array(['nabin', 'parth', 'parth', 'parth', 'parth', 'parth', 'vamsi',
       'vamsi', 'satish', 'satish'], dtype='<U6')

In [12]:
temp

array([54, 53, 84, 66, 35, 25, 83, 82, 47, 42])

In [13]:
a = list(zip(temp, name, random))

In [14]:
a

[(54, 'nabin', 12),
 (53, 'parth', 12),
 (84, 'parth', 13),
 (66, 'parth', 14),
 (35, 'parth', 10),
 (25, 'parth', 11),
 (83, 'vamsi', 13),
 (82, 'vamsi', 13),
 (47, 'satish', 14),
 (42, 'satish', 12)]

In [16]:
df = pd.DataFrame(data = a, columns=['temp','name','random'])

In [22]:
df

temp    name  random
0    80   parth      14
1    44   parth      13
2    89   vamsi      10
3    35   vamsi      12
4    92   nabin      14
5    37  satish      14
6    92   nabin      14
7    92   parth      14
8    91  satish      11
9    65  satish      10

In [17]:
type(df)

pandas.core.frame.DataFrame

In [23]:
import pandas as pd
import numpy as np

In [24]:
temp = np.random.randint(low = 20, high =100, size = [10,])
name = np.random.choice(['nabin','vamsi','parth','satish'],size=10)
random = np.random.choice([10,11,13,12,14],10)

In [18]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random})

In [19]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df

temp    name  random
0    54   nabin      12
1    53   parth      12
2    84   parth      13
3    66   parth      14
4    35   parth      10
5    25   parth      11
6    83   vamsi      13
7    82   vamsi      13
8    47  satish      14
9    42  satish      12

In [23]:
df.head(6)


temp   name  random
0    54  nabin      12
1    53  parth      12
2    84  parth      13
3    66  parth      14
4    35  parth      10
5    25  parth      11

In [26]:
df.tail(4)

temp    name  random
6    83   vamsi      13
7    82   vamsi      13
8    47  satish      14
9    42  satish      12

In [27]:
df.shape

(10, 3)

In [28]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [29]:
df.values

array([[54, 'nabin', 12],
       [53, 'parth', 12],
       [84, 'parth', 13],
       [66, 'parth', 14],
       [35, 'parth', 10],
       [25, 'parth', 11],
       [83, 'vamsi', 13],
       [82, 'vamsi', 13],
       [47, 'satish', 14],
       [42, 'satish', 12]], dtype=object)

In [30]:
# normal indexing is not support 
# it can support only slicing and dicing 
df[2:7]

temp   name  random
2    84  parth      13
3    66  parth      14
4    35  parth      10
5    25  parth      11
6    83  vamsi      13

In [31]:
df[2:9:3]

temp    name  random
2    84   parth      13
5    25   parth      11
8    47  satish      14

In [32]:
# access whole column data
df['random']

0    12
1    12
2    13
3    14
4    10
5    11
6    13
7    13
8    14
9    12
Name: random, dtype: int32

In [33]:
df.name

0     nabin
1     parth
2     parth
3     parth
4     parth
5     parth
6     vamsi
7     vamsi
8    satish
9    satish
Name: name, dtype: object

In [34]:
df['name']

0     nabin
1     parth
2     parth
3     parth
4     parth
5     parth
6     vamsi
7     vamsi
8    satish
9    satish
Name: name, dtype: object

In [35]:
df.describe()

temp     random
count  10.000000  10.000000
mean   57.100000  12.400000
std    20.999735   1.264911
min    25.000000  10.000000
25%    43.250000  12.000000
50%    53.500000  12.500000
75%    78.000000  13.000000
max    84.000000  14.000000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
temp      10 non-null int32
name      10 non-null object
random    10 non-null int32
dtypes: int32(2), object(1)
memory usage: 240.0+ bytes


In [47]:
df.values


array([[23, 'satish', 12],
       [48, 'vamsi', 13],
       [79, 'satish', 14],
       [27, 'vamsi', 14],
       [91, 'nabin', 13],
       [42, 'satish', 13],
       [20, 'satish', 14],
       [26, 'vamsi', 12],
       [87, 'satish', 13],
       [31, 'satish', 13]], dtype=object)

In [48]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [49]:
df

temp    name  random
0    23  satish      12
1    48   vamsi      13
2    79  satish      14
3    27   vamsi      14
4    91   nabin      13
5    42  satish      13
6    20  satish      14
7    26   vamsi      12
8    87  satish      13
9    31  satish      13

In [36]:
df.set_index('name', inplace = False)

temp  random
name                
nabin     54      12
parth     53      12
parth     84      13
parth     66      14
parth     35      10
parth     25      11
vamsi     83      13
vamsi     82      13
satish    47      14
satish    42      12

In [37]:
df

temp    name  random
0    54   nabin      12
1    53   parth      12
2    84   parth      13
3    66   parth      14
4    35   parth      10
5    25   parth      11
6    83   vamsi      13
7    82   vamsi      13
8    47  satish      14
9    42  satish      12

In [38]:
df.set_index('name',inplace=True)

In [39]:
df

temp  random
name                
nabin     54      12
parth     53      12
parth     84      13
parth     66      14
parth     35      10
parth     25      11
vamsi     83      13
vamsi     82      13
satish    47      14
satish    42      12

In [40]:
df.sort_index(axis =0, ascending=True)

temp  random
name                
nabin     54      12
parth     53      12
parth     84      13
parth     66      14
parth     35      10
parth     25      11
satish    47      14
satish    42      12
vamsi     83      13
vamsi     82      13

In [41]:
df

temp  random
name                
nabin     54      12
parth     53      12
parth     84      13
parth     66      14
parth     35      10
parth     25      11
vamsi     83      13
vamsi     82      13
satish    47      14
satish    42      12

In [42]:
df.sort_values(by ='random', ascending = True,inplace =True)

In [43]:
df

temp  random
name                
parth     35      10
parth     25      11
nabin     54      12
parth     53      12
satish    42      12
parth     84      13
vamsi     83      13
vamsi     82      13
parth     66      14
satish    47      14

In [44]:
df.drop(['random'], axis =1)

temp
name        
parth     35
parth     25
nabin     54
parth     53
satish    42
parth     84
vamsi     83
vamsi     82
parth     66
satish    47

In [45]:
df

temp  random
name                
parth     35      10
parth     25      11
nabin     54      12
parth     53      12
satish    42      12
parth     84      13
vamsi     83      13
vamsi     82      13
parth     66      14
satish    47      14

In [61]:
df.head()

temp  random
name                
satish    23      12
vamsi     26      12
vamsi     48      13
nabin     91      13
satish    42      13

In [62]:
df.iloc[[1,2]]

temp  random
name               
vamsi    26      12
vamsi    48      13

In [63]:
df.iloc[:,1]

name
satish    12
vamsi     12
vamsi     13
nabin     13
satish    13
satish    13
satish    13
satish    14
vamsi     14
satish    14
Name: random, dtype: int32

In [64]:
df.iloc[[True,True,False,True]]

temp  random
name                
satish    23      12
vamsi     26      12
nabin     91      13

In [46]:
df.set_index('random',inplace=True)

In [47]:
df

temp
random      
10        35
11        25
12        54
12        53
12        42
13        84
13        83
13        82
14        66
14        47

In [48]:
df.loc[14]


temp
random      
14        66
14        47

In [49]:
df.loc[14,'temp']

random
14    66
14    47
Name: temp, dtype: int32

In [50]:
df.loc[[11,12,13]]

temp
random      
11        25
12        54
12        53
12        42
13        84
13        83
13        82

In [51]:
df.loc[12:'temp']

temp
random      
12        54
12        53
12        42
13        84
13        83
13        82
14        66
14        47

In [52]:
df.loc[[True, True, False, True]]

temp
random      
10        35
11        25
12        53

In [53]:
df.loc[df.temp > 50]

temp
random      
12        54
12        53
13        84
13        83
13        82
14        66

In [54]:
df.loc[(df.temp <80) | (df.temp == 91),:]

temp
random      
10        35
11        25
12        54
12        53
12        42
14        66
14        47

In [6]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [56]:
# Merging & concat
d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [57]:
d1

col1  number
0    a       1
1    b       2

In [58]:
d2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [59]:
pd.concat([d1,d2],axis =0)

animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4

In [60]:
pd.concat([d1,d2], axis =0, ignore_index=True)

animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
2   lion  NaN      c       3
3  tiger  NaN      d       4

In [61]:
pd.concat([d1,d2], axis = 1)

col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [62]:
d1 = pd.DataFrame({
    "city" : ["lucknow","kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [63]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [64]:
d2 = pd.DataFrame({
    "city" : ["delhi","lucknow","kanpur"],
    "humidity" : [68,65,75]
})

In [87]:
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [88]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [65]:
df = pd.merge(d1,d2, on='city')

In [90]:
df

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [66]:
pd.merge(d1,d2, on=['city'], how ='outer')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [67]:
pd.merge(d1, d2, on =['city'], how='left')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [73]:
# dataset from https://github.com/codebasics/py/blob/master/pandas/6_handling_missing_data_replace/weather_data.csv

In [68]:
df1 = pd.read_csv("weather_data.csv")

In [69]:
df1

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [70]:
# pip3 install openpyxl
df1.to_excel('df_xl.xlsx', sheet_name = 'weather_data')

In [71]:
# pip3 install xlrd
df2 = pd.read_excel('df_xl.xlsx')

In [72]:
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [73]:
df2.to_csv('file.csv')

In [74]:
df2.to_csv('file_noindex.csv', index = False)

In [75]:
df_group = df2.groupby("event")

In [76]:
df_group

In [77]:
for temperature in df_group:
    print(temperature)

('Rain',         day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain)
('Snow',         day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow)
('Sunny',         day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
5  1/6/2017           31          2  Sunny)


In [78]:
df_group.get_group('Rain')

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [79]:
df_group.describe()

temperature                                               windspeed  \
            count  mean       std   min   25%   50%   75%   max     count   
event                                                                       
Rain          2.0  32.0  0.000000  32.0  32.0  32.0  32.0  32.0       2.0   
Snow          2.0  26.0  2.828427  24.0  25.0  26.0  27.0  28.0       2.0   
Sunny         2.0  33.0  2.828427  31.0  32.0  33.0  34.0  35.0       2.0   

                                                 
      mean       std  min   25%  50%   75%  max  
event                                            
Rain   5.0  1.414214  4.0  4.50  5.0  5.50  6.0  
Snow   4.5  3.535534  2.0  3.25  4.5  5.75  7.0  
Sunny  4.5  3.535534  2.0  3.25  4.5  5.75  7.0

In [80]:
def hot_temp(x):
    return x > 30

In [81]:
df2['hot_temp'] = df2['temperature'].apply(hot_temp)

In [82]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [108]:
df2['hot_temp'] = df2['temperature'].apply(lambda x: x > 30)

In [109]:
df2

day  temperature  windspeed  event  hot_temp
0  1/1/2017           32          6   Rain      True
1  1/2/2017           35          7  Sunny      True
2  1/3/2017           28          2   Snow     False
3  1/4/2017           24          7   Snow     False
4  1/5/2017           32          4   Rain      True
5  1/6/2017           31          2  Sunny      True

In [92]:
#pivot table

In [110]:
df2.pivot_table(values = 'temperature', index = 'event', aggfunc = 'mean')

temperature
event             
Rain            32
Snow            26
Sunny           33

In [83]:
df2.pivot_table(columns = 'temperature')

temperature     24     28    31    32    35
hot_temp     False  False  True  True  True
windspeed        7      2     2     5     7

In [96]:
help(pd.DataFrame.pivot_table)

Help on function pivot_table in module pandas.core.frame:

pivot_table(self, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')
    Create a spreadsheet-style pivot table as a DataFrame. The levels in
    the pivot table will be stored in MultiIndex objects (hierarchical
    indexes) on the index and columns of the result DataFrame
    
    Parameters
    ----------
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed,
        it is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The
        list can contain any of the other types